// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1305.PowerUpDemo;

import org.usfirst.frc1305.PowerUpDemo.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
      
    public Joystick xbox1 = new Joystick(0);  // Primary Driver Stick
    
	Button btn1_A = new JoystickButton(xbox1, 1);  //xbox "A" Button 1
	Button btn1_B = new JoystickButton(xbox1, 2); //xbox "B" Button 2
	Button btn1_X = new JoystickButton(xbox1, 3); //xbox "X" Button 3
	Button btn1_Y = new JoystickButton(xbox1, 4); //xbox "Y" Button 4
	Button btn1_LB = new JoystickButton(xbox1, 5); //xbox "LB" Button 5
	Button btn1_RB = new JoystickButton(xbox1, 6);  //xbox "RB" Button 6
	Button btn1_Back = new JoystickButton(xbox1, 7);  //xbox "Back" Button 7
	Button btn1_Start = new JoystickButton(xbox1, 8);  //xbox "Start" Button 8
	Button btn1_LS = new JoystickButton(xbox1, 9);  //xbox "Left Stick Click" Button 9
	Button btn1_RS = new JoystickButton(xbox1, 10);  //xbox "Right Stick Click" Button 10

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public Joystick xbox2 = new Joystick(1);  // Secondary Driver Stick
    
	Button btn2_A = new JoystickButton(xbox2, 1);  //xbox "A" Button 1
	Button btn2_B = new JoystickButton(xbox2, 2); //xbox "B" Button 2
	Button btn2_X = new JoystickButton(xbox2, 3); //xbox "X" Button 3
	Button btn2_Y = new JoystickButton(xbox2, 4); //xbox "Y" Button 4
	Button btn2_LB = new JoystickButton(xbox2, 5); //xbox "LB" Button 5
	Button btn2_RB = new JoystickButton(xbox2, 6);  //xbox "RB" Button 6
	Button btn2_Back = new JoystickButton(xbox2, 7);  //xbox "Back" Button 7
	Button btn2_Start = new JoystickButton(xbox2, 8);  //xbox "Start" Button 8
	Button btn2_LS = new JoystickButton(xbox2, 9);  //xbox "Left Stick Click" Button 9
	Button btn2_RS = new JoystickButton(xbox2, 10);  //xbox "Right Stick Click" Button 10

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	
    	
        // button.whenPressed(new ExampleCommand());
        // button.whileHeld(new ExampleCommand());
        // button.whenReleased(new ExampleCommand());

    	// Primary Driver Stick
    	btn1_A.whenPressed(new Cmd_Arm_Toggle());//xbox "A" Button 1
    	btn1_B.whenPressed(new Cmd_LED_Blink());//xbox "B" Button 2
    	btn1_X.whileHeld(new Cmd_Intake_Out());//xbox "X" Button 3
    	btn1_Y.whileHeld(new Cmd_Intake_In());//xbox "Y" Button 4
    	btn1_LB.whileHeld(new Cmd_Intake_Out());//xbox "LB" Button 5
    	btn1_RB.whileHeld(new Cmd_Intake_In());//xbox "RB" Button 6
    	btn1_Back.whileHeld(new Cmd_LED_Blink());//xbox "Back" Button 7
    	btn1_Start.whileHeld(new Cmd_LED_Blink());//xbox "Start" Button 8
    	btn1_LS.whileHeld(new Cmd_LED_Blink());//xbox "Left Stick Click" Button 9
    	btn1_RS.whileHeld(new Cmd_LED_Blink());//xbox "Right Stick Click" Button 10
    	////xbox "X Axis" Left Stick - 
    	////xbox "Y Axis" Left Stick - Drive Forward and Reverse
    	////xbox "X Axis 5" Right Stick - 
    	////xbox "Y Axis 4" Right Stick - Drive Left and Right
    	////xbox "Axis 3" Left Trigger - 
    	////xbox "Axis 3" Right Trigger - 
    	////xbox "Up" Direction Pad - 
    	////xbox "Down" Direction Pad - 
    	////xbox "Left" Direction Pad - 
    	////xbox "Right" Direction Pad - 
    	
        
    	// Secondary Driver Stick
    	btn2_A.whenPressed(new Cmd_Arm_Toggle());//xbox "A" Button 1
    	btn2_B.whileHeld(new Cmd_LED_Blink());//xbox "B" Button 2
    	btn2_X.whileHeld(new Cmd_Intake_Out());//xbox "X" Button 3
    	btn2_Y.whileHeld(new Cmd_Intake_In());//xbox "Y" Button 4
    	btn2_LB.whileHeld(new Cmd_Intake_Out());//xbox "LB" Button 5
    	btn2_RB.whileHeld(new Cmd_Intake_In());//xbox "RB" Button 6
    	btn2_Back.whileHeld(new Cmd_LED_Blink());//xbox "Back" Button 7
    	btn2_Start.whileHeld(new Cmd_LED_Blink());//xbox "Start" Button 8
    	btn2_LS.whileHeld(new Cmd_LED_Blink());//xbox "Left Stick Click" Button 9
    	btn2_RS.whileHeld(new Cmd_LED_Blink());//xbox "Right Stick Click" Button 10
    	////xbox "X Axis" Left Stick - 
    	////xbox "Y Axis" Left Stick - Stage 2 Move  
    	////xbox "X Axis 5" Right Stick - Stage 1 Move
    	////xbox "Y Axis 4" Right Stick - 
    	////xbox "Axis 3" Left Trigger - 
    	////xbox "Axis 3" Right Trigger - 
    	////xbox "Up" Direction Pad - 
    	////xbox "Down" Direction Pad - 
    	////xbox "Left" Direction Pad - 
    	////xbox "Right" Direction Pad - 
        

        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        ////SmartDashboard.putData("IntakeCommand", new IntakeCommand());
        ////SmartDashboard.putData("DrivewithJoyStick", new DrivewithJoyStick());
        ////SmartDashboard.putData("IntakeRevCommand", new IntakeRevCommand());
        ////SmartDashboard.putData("Abutton", new Abutton());
        ////SmartDashboard.putData("Bbutton", new Bbutton());
        ////SmartDashboard.putData("Ybutton", new Ybutton());
        ////SmartDashboard.putData("Xbutton", new Xbutton());
        ////SmartDashboard.putData("RTtop", new RTtop());
        ////SmartDashboard.putData("LTtop", new LTtop());
        ////SmartDashboard.putData("ElevatorLoop", new ElevatorLoop());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystickDrive() {
        return xbox1;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick2() {
        return xbox2;
    }
    
    
}

