// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1305.PowerUpDemo.subsystems;


import org.usfirst.frc1305.PowerUpDemo.RobotMap;

import com.ctre.phoenix.CANifier;
import com.ctre.phoenix.CANifier.LEDChannel;

import edu.wpi.first.wpilibj.command.Subsystem;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class RGBledCAN extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANifier LEDcontroller = RobotMap.RGBLEDController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	double power;
	double brightness;

    @Override
    
  
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void LEDoff() {
    	 	LEDcontroller.setLEDOutput(0.0, LEDChannel.LEDChannelA);	//Blue
    	 	LEDcontroller.setLEDOutput(0.0, LEDChannel.LEDChannelB);	//Red
    	 	LEDcontroller.setLEDOutput(0.0, LEDChannel.LEDChannelC);	//Green
    }
    
    public void LEDred() {	
	 	//.setLEDOutput(0.0, LEDChannel.LEDChannelA);	//Blue
	 	LEDcontroller.setLEDOutput(1.0, LEDChannel.LEDChannelB);	//Red
	 	//LEDcontroller.setLEDOutput(0.0, LEDChannel.LEDChannelC);	//Green

    }
    
    public void LEDgreen() {
	 	//LEDcontroller.setLEDOutput(0.0, LEDChannel.LEDChannelA);	//Blue
	 	//LEDcontroller.setLEDOutput(0.0, LEDChannel.LEDChannelB);	//Red
	 	LEDcontroller.setLEDOutput(1.0, LEDChannel.LEDChannelC);	//Green
    }
    
    public void LEDblue() {
	 	LEDcontroller.setLEDOutput(1.0, LEDChannel.LEDChannelA);	//Blue
	 	//LEDcontroller.setLEDOutput(0.0, LEDChannel.LEDChannelB);	//Red
	 	//LEDcontroller.setLEDOutput(0.0, LEDChannel.LEDChannelC);	//Green
    }
    
    public void LEDbluelow() {
	 	LEDcontroller.setLEDOutput(0.1, LEDChannel.LEDChannelA);	//Blue
	 	//LEDcontroller.setLEDOutput(0.0, LEDChannel.LEDChannelB);	//Red
	 	//LEDcontroller.setLEDOutput(0.0, LEDChannel.LEDChannelC);	//Green
    }
    
    public void LEDbluePower(double power) {
    	LEDcontroller.setLEDOutput(power, LEDChannel.LEDChannelA);	//Blue
	 	//LEDcontroller.setLEDOutput(0.0, LEDChannel.LEDChannelB);	//Red
	 	//LEDcontroller.setLEDOutput(0.0, LEDChannel.LEDChannelC);	//Green
    } 	
    
    public void LEDyellow() {
	 	//LEDcontroller.setLEDOutput(0.0, LEDChannel.LEDChannelA);	//Blue
	 	LEDcontroller.setLEDOutput(1.0, LEDChannel.LEDChannelB);	//Red
	 	LEDcontroller.setLEDOutput(1.0, LEDChannel.LEDChannelC);	//Green
    }
    
    public void LEDcyan() {
	 	LEDcontroller.setLEDOutput(1.0, LEDChannel.LEDChannelA);	//Blue
	 	//LEDcontroller.setLEDOutput(0.0, LEDChannel.LEDChannelB);	//Red
	 	LEDcontroller.setLEDOutput(1.0, LEDChannel.LEDChannelC);	//Green	
    }
    public void LEDmagenta() {
	 	LEDcontroller.setLEDOutput(1.0, LEDChannel.LEDChannelA);	//Blue
	 	LEDcontroller.setLEDOutput(1.0, LEDChannel.LEDChannelB);	//Red
	 	//LEDcontroller.setLEDOutput(0.0, LEDChannel.LEDChannelC);	//Green
    }
    public void LEDwhite() {
	 	LEDcontroller.setLEDOutput(1.0, LEDChannel.LEDChannelA);	//Blue
	 	//LEDcontroller.setLEDOutput(1.0, LEDChannel.LEDChannelB);	//Red
	 	
	 	
	 	//LEDcontroller.setLEDOutput(1.0, LEDChannel.LEDChannelC);	//Green
    		
    }
    

}

