// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1305.PowerUpDemo.subsystems;

import org.usfirst.frc1305.PowerUpDemo.RobotMap;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Solenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class RGBledPCM extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Solenoid blueSolenoid = RobotMap.blueSolenoid;
    private final Solenoid greenSolenoid = RobotMap.greenSolenoid;
    private final Solenoid redSolenoid = RobotMap.redSolenoid;
    private final Solenoid commonSolenoid = RobotMap.commonSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void LEDoff() {
    	commonSolenoid.set(false);
    	redSolenoid.set(false);
    	greenSolenoid.set(false);
    	blueSolenoid.set(false); 	
    }
    
    public void LEDred() {
    	commonSolenoid.set(true);
    	redSolenoid.set(true);
    	greenSolenoid.set(false);
    	blueSolenoid.set(false); 	
    }
    
    public void LEDgreen() {
    	commonSolenoid.set(true);
    	redSolenoid.set(false);
    	greenSolenoid.set(true);
    	blueSolenoid.set(false); 	
    }
    
    public void LEDblue() {
    	commonSolenoid.set(true);
    	redSolenoid.set(false);
    	greenSolenoid.set(false);
    	blueSolenoid.set(true); 	
    }
    
    public void LEDyellow() {
    	commonSolenoid.set(true);
    	redSolenoid.set(true);
    	greenSolenoid.set(true);
    	blueSolenoid.set(false); 	
    }
    
    public void LEDcyan() {
    	commonSolenoid.set(true);
    	redSolenoid.set(false);
    	greenSolenoid.set(true);
    	blueSolenoid.set(true); 	
    }
    public void LEDpink() {
    	commonSolenoid.set(true);
    	redSolenoid.set(true);
    	greenSolenoid.set(false);
    	blueSolenoid.set(true); 	
    }
    public void LEDwhite() {
    	commonSolenoid.set(true);
    	redSolenoid.set(true);
    	greenSolenoid.set(true);
    	blueSolenoid.set(true); 	
    }
    

}

